> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Some Numpy Functions and their working


### Some Most commonly used Numpy functions

NumPy is a Python library used for working with arrays.

NumPy was created in 2005 and is an open source project that you can use it freely.

- np.min
- np.dot
- np.flip
- np.reshape
- np.ravel

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [64]:
!pip install jovian --upgrade -q


[notice] A new release of pip available: 22.3.1 -> 23.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [65]:
import jovian

In [73]:
jovian.commit(filename='numpy-array-operations')


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [67]:
import numpy as np

In [68]:
 
function1 = np.min 
function2 = np.dot
function3 = np.flip
function4 = np.reshape
function5 = np.ravel

## Function 1 - np.min

This function is used to find the minimum value in an array which is very useful when we are finding the most minimum value in a dataset

In [69]:
# Example 1 - working 
arr1 = [7,2,3,4]

np.min(arr1)

2

The above function find the minimum in a list of elements

In [70]:
# Example 2 - working
a=np.array([[3,1,2],[7,6,5]])
np.min(a)

1

Even in a multidimensional array the function checks through each and every element to give us the minimum value

In [71]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([[3,2,1],[9,8,7,5]])
np.min(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

The Reason why it breaks is because the declaration of the array is wrong 
The sizes of the array in one-dimension muct match else it becomes inhomogenous

It can be corrected by:

a=np.array([[a,b,c],[d,e,f]])

np.min(a)

It is used when we need to find the minimum value in a dataset

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

# Function 2 - np.dot
This function is used to find the dot product of two arrays

In [ ]:
# Example 1 - working
a=np.array([1,2,3])
b=np.array([4,5,6])
np.dot(a,b)

32

Just calculated the dot product of two 1-D arrays

In [ ]:
# Example 2 - working
a=np.array([[1,2],[4,5]])
b=np.array([[7,8],[1,5]])

np.dot(a,b)

array([[ 9, 18],
       [33, 57]])

Dot product of a 2-D array

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[1,5,9]])

np.dot(a,b)


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

The dot product doesn't work here because the shapes of the array are not adhering to the rules of the dot product

This function is used when we want to find the dot product of two elements of an array

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

# Function 3 - np.filp

This function here is used to flip all the elemnts in an array, Its similar to reversing an array

In [ ]:
# Example 1 - working
a=np.array([1,2,3,4,5])
np.flip(a)

array([5, 4, 3, 2, 1])

In the above Example we have flipped the array i.e. We have just revesed it

In [ ]:
# Example 2 - working
a=np.array([[1,2,3],[4,3,2]])
np.flip(a)

array([[2, 3, 4],
       [3, 2, 1]])

When working with a multidimensional array, the function reverses it from the outside to inside i.e. it first reverses the outer array then it reverses the elements present in the inner array

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([[3,2,1],[9,8,7,5]])
np.flip(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

The np.flip is a rather easy function and you will not run into any errors given the array is correct
In the above example we had a break in the program because the array declaration was wrong i.e. size of the array was inhomogenous i.e. not equal

the corrected way would be:

a=np.array[[1,2,3],[7,5,4]]
np.flip(a)

The above example will work

This function can be used when we want to reverse the array

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - np.reshape

Help in reshaping the array to our desired shape

In [ ]:
# Example 1 - working
a=np.array([4,3,2,1,5,4])
a.reshape(2,3)

array([[4, 3, 2],
       [1, 5, 4]])

Explanation about example

In [ ]:
# Example 2 - working
a=np.array([[3,2],[4,5]])
a.reshape([4,1])

array([[3],
       [2],
       [4],
       [5]])

We have reshaped the array form size 2,2 to 4,1

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([[3,2],[4,5]])
a.reshape([1,1])

ValueError: cannot reshape array of size 4 into shape (1,1)

This doesnt work because the array resize must include all the elements of an array 

but the declaration above doesnt include all elements leading to no reshaping 

declaration a.reshape(1,4) works and converts the array into 1-D array

This is mainly used when we want to reshape an array so that when performing some numpy oeprations on an array we have arrays to equal shapes

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - np.ravel

It is used to flatten an array

In [ ]:
# Example 1 - working
a=np.array([[1,2,3],[4,2,1]])
np.ravel(a)


array([1, 2, 3, 4, 2, 1])

It flattens the 2-D array into a 1-D array

In [ ]:
# Example 2 - working
a=np.array([[[3,2,1],[5,4,3]],
           [[4,3,2],[5,4,3]]])
np.ravel(a)

array([3, 2, 1, 5, 4, 3, 4, 3, 2, 5, 4, 3])

Flattening out a 3-D array

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.array([[[3,2,1],[5,4,3]]
           [[4,3,2],[5,4,3]]])
np.ravel(a)

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\rafiq\AppData\Local\Temp\ipykernel_18196\3786178433.py:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([[[3,2,1],[5,4,3]]


TypeError: list indices must be integers or slices, not tuple

The common error that includes which leads to the breaking of the code is in the declaration of the array

If the array is declared wrong as in the above it leads to an error

a=np.array(
    
           [[[3,2,1],[5,4,3]],->the comma here was missed in the above leading to a missing comma error

           [[4,3,2],[5,4,3]]])

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>